### ISSUE TITLE
[QUESTION] Can you download paket.bootstrapper.exe?

### ISSUE THREAD

**Issue by gep13** [larzw/Cake.Paket.Example#1]
First up, thank you very much for creating this example!

I am not a user of paket, so I could be completely off here, but we normally recommend that no binaries are checked into source control.  I noticed that you have the paket.bootstrapper.exe already in the .paket folder.  Is it not possible to download and execute this exe within the bootstrapper, rather than check it into source control?  Thanks!

**Comment by larzw** [comment]
Thanks @gep13 for the question. I added a section to the [README.md](https://github.com/larzw/Cake.Paket.Example#committing-binary-files) file that discusses this and includes a code snippet showing how to modify the boostrapper scripts to accomplish this. However, as per pakets getting started guide

> "Commit .paket/paket.bootstrapper.exe into your repo and add .paket/paket.exe to your .gitignore file."[[Ref]](https://fsprojects.github.io/Paket/getting-started.html) 

I've decided to keep it committed in this example project.

**Comment by larzw** [comment]
On second thought @gep13 I added a command line argument to the scripts so the user has the ability to provide a URL to download paket.boostraper.exe: `.\build.ps1 -PaketBootStrapperURL "Add URL Here"` and/or `./build.sh -b "Add URL Here".` Thanks for the idea!

**Comment by gep13** [comment]
Sounds good to me.

Another quick question...

What exactly does the paket.bootstrapper.exe do?  Is it just downloading the main paket.exe?  If so, can you not simply have the bootstrapper.ps1 file do that download?

**Comment by larzw** [comment]
You could download paket.exe directly if you wanted/needed to. However, I probably would not. The paket.bootstrapper.exe has some command line arguments and ability's when it comes to dealing with paket.exe...[see bootstrapper docs](https://fsprojects.github.io/Paket/bootstrapper.html). For example, paket.exe changes on a regular basis and the bootstrapper will automatically get the latest stable version for you.
